version: "3"

services:
  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    # и снова мониторуем директорию nginx
    volumes:
      - ../nginx/:/etc/nginx/
    build:
      context: .
      dockerfile: Dockerfile
      # задаем переменные среды
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
        SUB_DOMAIN_URL: ${SUB_DOMAIN_URL}
